title: Default Page
# icon: 📝

columns:
  info:
    type: fields
    width: 1/2
    fields:
      description:
        type: textarea
      link:
        type: url
        help: This will cause the heading to link out directly.
  files:
    width: 1/2
    sections:
      linklist:
        type: fields
        fields:
          links:
            type: structure
            fields:
              title:
                type: text
              target:
                type: link
                label: Link
                options:
                  - url
                  - email
                  - tel
                settings: false
      filelist:
        type: fields
        fields:
          docs:
            label: Documents
            type: structure
            fields:
              title:
                type: text
              target:
                type: files
                label: File
      subpages:
        type: pages
        template: default

  gallery:
    width: 1/1
    sections:
      lightbox:
        type: files
        layout: card
        template: image
        help: Images, videos, and sound files will be displayed in the carousel in the order they appear above.
