title: Default Page
# icon: 📝

columns:
  - width: 1/2
    fields:
      description:
        type: textarea
        size: medium
      link:
        type: url
        help: This will cause the section to link out directly to given URL.

  - width: 1/2
    sections:
      linklist:
        type: fields
        fields:
          links:
            type: structure
            fields:
              title:
                type: text
              target:
                type: link
                label: Link
                options:
                  - url
                  - tel
                  - email
                settings: false
      doclist:
        type: fields
        fields:
          docs:
            label: Documents
            type: structure
            fields:
              title:
                type: text
              target:
                type: files
                label: File
      subpages:
        type: pages
        template: default

  - width: 1/1
    sections:
      gallery:
        type: files
        layout: cards
        info: "{{ file.dimensions }}"
        template: carousel
        image:
          ratio: 5/4
          cover: true
        size: small
        help: Images, videos, and sound files will be displayed in the carousel in the order they appear above.
